batch_size: 128
learning_rate: 0.01
epochs: 300
sigma: 5.
lambda_x: 0.
lambda_y: 0.
seed: 1234
k_type_y: linear

device: cuda
model: resnet18
data_code: cifar10
model_file: test.pt
checkpoint: null
task: pre-train
training_type: hsictrain

lr_scheduler :  cosine
warmup :  False
warmup_lr :  0.0001
warmup_epochs :  5
mix_up :  False
alpha :  0.3
smooth :  False
smooth_eps :  0
log_batch_interval: 10
verbose: 0
exp_index: null
do_training: True

xentropy_weight: 0.
hsic_weight: 1.

attack_type: pgd
epsilon: 8
pgd_steps: 10
pgd_alpha: 2
