batch_size: 256
learning_rate: 0.0001
epochs: 100
sigma: 5.
seed: 1234

device: cuda
model: lenet3
data_code: mnist
model_file: backprop_lenet_mnist.pt
task: pre-train
training_type: backprop

log_batch_interval: 10
verbose: 0
ext: pdf
exp_index: null
do_training: True


